NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    # === авторизация ===
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
]

news/urls.py
from django.urls import path
from .views import NewsList, NewsDetail, CategoryDetail, SearchListViews, PostCreateView, PostUpdateView, PostDeleteView  #, add_like
from .views import PostAuthorView
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    # path('', NewsList.as_view(), name='post_list'),
    path('news/', NewsList.as_view(), name='post_list'),
    # path('news/<str:slug>/', NewsDetail.as_view(), name='post_detail'), # отображение заголовка в адресной строке
    path('news/<int:pk>/', NewsDetail.as_view(), name='post_detail'),  # возможен переход по id статьи\новости
    path('category/<int:pk>/', CategoryDetail.as_view(), name='category_detail'),
    path('search/', SearchListViews.as_view(), name='search'),
    # path('like/', add_like, name='add_like'),  # не знаю как сделать
    path('add/', PostCreateView.as_view(), name='post_create_view'),
    path('<int:pk>/edit/', PostUpdateView.as_view(), name='post_update_view'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete_view'),
    path('my_post/', PostAuthorView.as_view(), name='post_author_view'),
    # path('password_change/', auth_views.PasswordChangeView.as_view(),
    #      name='password_change'),
    path('category/subscribers/', views.follow_user, name='follow'),
    path('category/unsubscribers/', views.unfollow_user, name='unfollow'),
]

news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.urls import reverse
from django.utils import timezone
from django.utils.datetime_safe import datetime
from django.utils.text import slugify


class Author(models.Model):
    """ Модель Автора. Модель рейтинга с дефолтным значение равное 0"""
    author_user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Автор')
    author_rating = models.SmallIntegerField(default=0, verbose_name='Рейтинг автора')

    " Функция подсчета рейтинга пользователя "
    def update_rating(self):
        rating_post = self.post_set.aggregate(postRating=Sum('post_rating'))
        postRat = 0
        postRat += rating_post.get('postRating')
        print(postRat)

        rating_comment = self.author_user.comment_set.aggregate(commentRating=Sum('comment_rating'))
        comRat = 0
        comRat += rating_comment.get('commentRating')

        self.author_rating = postRat * 3 + comRat
        self.save()

    " Возвращает автора с наивысшим рейтингом "
    @staticmethod
    def best_author():
        return Author.objects.all().order_by('-author_rating')[0]

    def __str__(self):
        return f"{self.author_user}"

    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'


class Category(models.Model):
    """ Модель Category(КАТЕГОРИЯ) связующая модель CategorySubscribers(ПОДПИСЧИКОВ НА КАТЕГОРИЮ) """
    category_name = models.CharField(max_length=64, unique=True, verbose_name='Имя категории')
    subscribers = models.ManyToManyField(User, blank=True, through='CategorySubscribers')

    def __str__(self):
        # return f"Категория: {self.category_name}"
        return '{}'.format(self.category_name)

    def save(self, *args, **kwargs):
        if not self.category_name:
            self.category_name = slugify(str(self.category_name))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class CategorySubscribers(models.Model):
    """ Модель ПОДПИСКИ на КАТЕОРИЮ """
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL, verbose_name='Категория')
    subscriber_user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, verbose_name='Подписчик')
    # category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    # subscriber_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Подписчик')

    def __str__(self):
        # return f"Подписка на категорию: {self.category}, {self.subscriber_user}"
        return f'{self.subscriber_user} подписан на категорию {self.category}'

    class Meta:
        verbose_name = 'Категория подписки'
        verbose_name_plural = 'Категории подписок'


class Post(models.Model):
    """ Модель выбора публикации СТАТЬИ или НОВОСТИ.
     Эта модель должна содержать в себе статьи или новости, которые создают пользователи"""
    post_article = 'PA'
    post_news = 'PN'

    POSITIONS = ((post_article, 'Статья'), (post_news, 'Новость'))
    position = models.CharField('Тип', max_length=2, choices=POSITIONS, default=post_article)

    post_author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор')
    slug = models.CharField(max_length=250, db_index=True)

    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    updated_date = models.DateTimeField(auto_now=True)
    post_category = models.ManyToManyField(Category, through='PostCategory', help_text='Соединить категорию')
    headline = models.CharField(max_length=128, name=False, verbose_name='Заголовок')
    post_text = models.TextField(null=False, verbose_name='Текст')
    post_rating = models.SmallIntegerField(default=0, verbose_name='Рейтинг')

    " Добавим абсолютный путь чтобы после создания нас перебрасывало на главную страницу "
    def get_absolute_url(self):
        # return reverse('news:post_detail', kwargs={"slug": self.slug})
        return reverse('post_detail', kwargs={"pk": self.pk})  # возможен переход по id статьи\новости

    def save(self, *args, **kwargs):
        value = self.headline
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def like(self):
        self.post_rating += 1
        self.save()

    def dislike(self):
        self.post_rating -= 1
        self.save()

    def preview(self):
        # return self.headline[0:124] + '...'
        return '{0}...{1}'.format(self.headline[0:124], "...")

    " Строковое отображение поста "
    def __str__(self):
        return f"Автор: {self.post_author.author_user.first_name}, Заголовок: {self.headline}, Текст: {self.post_text}, Рейтинг: {self.post_rating}"

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'


class PostCategory(models.Model):
    """ Промежуточная модель для связи «многие ко многим» """
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост в категории')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')

    def __str__(self):
        return f'{self.category}, Пост: {self.post}'

    class Meta:
        verbose_name = 'Связь категории'
        verbose_name_plural = 'Связь категории'


class Comment(models.Model):
    """ Модуль хранения комментариев под постами """
    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    comment_text = models.TextField(verbose_name='Текст комментария')
    comment_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')
    comment_rating = models.SmallIntegerField(default=0, verbose_name='Рейтинг комментария')

    def like(self):
        self.comment_rating += 1
        self.save()

    def dislike(self):
        self.comment_rating -= 1
        self.save()

    # " Выводит все комментарии из поста с наивысшим рейтингом "
    # @staticmethod
    # def all_comments_for_best_post():
    #     best_post = Comment.objects.filter(post=Post.find_best_post())
    #     for i in best_post:
    #         print(i)

    " Строковое отображение комментария "
    def __str__(self):
        return 'Пользователь: {} Текст: {} Рейтинг: {} * '.format(self.comment_user, self.comment_text, self.comment_rating)
        # return f'Пользователь: {self.comment_user}, Текст: {self.comment_text}, Рейтинг: {self.comment_rating}, {self.comment_post}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


# =================== GROUP ==============================
# @receiver(user_signed_up)
# def user_signed_up_(request, user, **kwargs):
#     Group.objects.get(name='common').user_set.add(user)
#     user.save()

news/forms.py
from django.forms import ModelForm, Select, Textarea, TextInput, SelectMultiple, CharField
from .models import Post, Comment


class PostForm(ModelForm):
    # check_box = BooleanField(label='Ало, Галочка!')
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['post_author'].empty_label = 'Автор не выбран'

    class Meta:
        model = Post
        # fields = ['post_author', 'headline', 'position', 'post_category', 'post_text', ]
        fields = ['headline', 'position', 'post_category', 'post_text', ]

        widgets = {
            'headline': TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Заголовок поста'
            }),
            'post_text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите текст...'
            }),
            # 'post_author__author_user': Select(attrs={
            #     'class': 'custom-select',
            #     'option selected': 'Выбрать автора'
            # }),
            'position': Select(attrs={
                'class': 'custom-select',
                'option selected': 'Выбрать тип'
            }),
            'post_category': SelectMultiple(attrs={
                'multiple class': 'form-control',
            }),
        }


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'
        # fields = ['comment_user', 'comment_text', ]
        fields = ['comment_text', ]

        widgets = {
            # 'comment_user': Select(attrs={
            #     'class': 'custom-select',
            #     'option selected': 'Выбрать автора'
            # }),
            'comment_text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите текст...'
            }),
        }

news/templates/news/author_list.html
{% extends 'default.html' %}
{% load custom_filters %}

{% block title %} МОИ ПУБЛИКАЦИИ {% endblock %}


{% block content %}
<div>
    <h1> {{ time_now|date:'d F Y H:i'}}</h1>
</div>
<div class="container">
    <h3> Моя подписка на выбранные категории: </h3>
    {% for sub in my_subscribers %}
    <strong><q> {{ sub.category }} </q></strong>
    {% endfor %}
</div>
<hr>
<div class="container">
    <h4>МОИ ПУБЛИКАЦИИ</h4>
    {% if my_author %}
    <table class="table" style="margin: auto; width: auto">
        <thead>
        <tr>
            <th>ЗАГОЛОВОК</th>
            <th>ДАТА ПУБЛИКАЦИИ</th>
            <th>ТЕКСТ ПОСТА</th>
            <th>РЕЙТИНГ ПОСТА</th>
            <th>АВТОР ПОСТА</th>
            <th>РЕЙТИНГ АВТОРА</th>
            <th>ТИП</th>
            <th>КАТЕГОРИЯ</th>
        </tr>
        </thead>
        <tbody>
        {% for p in my_author %}
        <tr>
            <td><a href="{{ p.get_absolute_url }}"> {{ p.headline|censor }} </a></td>
            <td>{{ p.create_date|date:'d F Y' }}</td>
            <td>{{ p.post_text|truncatechars:50|censor }}</td>
            <td><b>{{ p.post_rating }}</b></td>
            <td>{{ p.post_author.author_user.first_name}} {{p.post_author.author_user.last_name}}</td>
            <td> {{ p.post_author.author_rating }}</td>
            <td> {{ p.get_position_display }}</td>
            <td> {{ p.post_category }}</td>
        </tr>
        {% endfor %}
        <tbody>
    </table>
    {% else %}
    <h2> ВЫ ЕЩЕ НЕ НАПИСАЛИ ПУБЛИКАЦИИ КАК АВТОР </h2>
    {% endif %}
</div>

{% endblock %}

news/templates/news/category_detail.html
{% extends 'default.html' %}
{% load custom_filters %}
{% block title %} {{ category_detail.category_name }} {% endblock %}


{% block content %}
<div class="container m-auto"><input type="button" class="btn btn-light btn-outline-info" onclick="history.back();"
                                     value="Назад"/></div>
<br>
<div class="container">
    <h2> Все посты из категории <q>{{ category_detail.category_name }}</q></h2>
    <div>
        {% if is_subscribers %}
        <b>Если больше не желаете получать уведомление о новых новостях, нажмите отписаться</b>
        <a class="btn" href="{% url 'unfollow' %}"><button type="submit" value="unfollow" name="pk" class="btn btn-light btn-outline-danger"> Отписаться</button></a>
        {% else %}
        <b>Если хотите получать уведомления о новых новостях, вы можете подписаться на данную категорию</b>
        <a class="btn" href="{% url 'follow' %}"><button type="submit" value="follow" name="pk" class="btn btn-light btn-outline-primary"> Подписаться</button></a>
        {% endif %}
    </div>
    <hr>
    <div>
        {% if category_detail %}
        {% for post in category_news %}++++++
        <strong> <a href="{{ post.get_absolute_url }}"> Заголовок: {{ post.headline|censor }} </a> </strong>
        <p> Текст: {{ post.post_text|truncatewords:1|censor }} <strong> рейтинг: {{ post.post_rating }} </strong></p>
        <q> Автор: {{ post.post_author }} ***** рейтинг автора: {{ post.post_author.author_rating }}</q>
        <p>∗ {{ post.create_date|date:'d M Y h:i' }} ∗ </p>
        <p><q>&lowast;&lowast;&lowast;</q></p>
        {% endfor %}
        {% endif %}
    </div>
</div>


{% endblock %}

news/templates/news/post_confirm_delete.html
{% extends 'default.html' %}
{% load custom_filters %}

{% block title %} Удаление статьи {% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-xl-10 mx-auto">
            <h2>Вы действительно хотите удалить данный пост?</h2> <br>

            <div>
                <p class="post-title"> Заголовок: {{ post.headline|censor }} </p>
                <p style="text-align: justify;">Текс: {{ post.post_text }}</p>
                <p class="post-meta"><strong></strong>Post by
                    <strong>{{ post.post_author }}</strong>
                    Дата публикации: {{ post.create_date|date:'d M Y h:m' }}</p>
            </div>

            <br>
            <form method="POST">
                {% csrf_token %}
                <p> {{ post_text }}</p>
                <input class=" btn btn-danger mx-auto" type="submit" value="подтвердить">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

news/templates/news/post_detail.html
{% extends 'default.html' %}
{% load custom_filters %}
{% block title %} {{ post_detail.headline }} {% endblock %}


{% block content %}
<div class="rat">
    <h3>Категория: {% for pc in post_category %} {{ pc }}, {% endfor %}</h3>
    <input type="button" class="btn btn-light btn-outline-info" onclick="history.back(-3);" value="Назад"/>
</div>
<hr>
<div>
    <h4> Заголовок: ** {{ post_detail.headline|censor }} ** </h4>
    <p><b>Текст:</b> {{ post_detail.post_text|censor }} </p>
    <p><b> Рейтинг поста: {{ post_detail.post_rating }} </b> &#61;&#61; <em><b>{{post_detail.create_date|date:'d M Y'}}</b></em><br>
        <q>Автор текста: <strong>{{ post_detail.post_author.author_user.first_name }}</strong> &#151;
            Рейтинг автора: {{ post_detail.post_author.author_rating }}</q></p>
</div>
<strong><q>&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;&#61;</q></strong>
<p><a href="{% url 'post_update_view' post_detail.id %}" style="text-align: right;"><u>Редактировать пост</u></a></p>
<p><a href="{% url 'post_delete_view' post_detail.id %}" style="text-align: right;"><u> Удалить </u></a></p>

<!--============================ LIKE \ DESLIKE ================================================-->
<div>
    <form action="" method="" class="btn">
        {% csrf_token %}
        <button type="submit" value="{{ post_detail.pk }}" name="pk" class="btn btn-light btn-outline-primary"> &#43;
        </button>
    </form>

    <strong> Поставь лайк </strong>
    {{ post_detail.post_rating }}

    <form action="" method="" class="btn">
        {% csrf_token %}
        <button type="submit" value="{{ post_detail.pk }}" name="pk" class="btn btn-light btn-outline-danger"> &#45;
        </button>
    </form>
</div>

<!--=================================== КОММЕНТАРИИ ================================================================-->
<hr> <h3> &lowast; Комментарии &lowast; </h3>
<b> --------------- </b>
<div>
    {% if comment_list %}
    {% for comments in comment_list %}
    <a> {{ comments.comment_user.first_name }} &lowast; {{ comments.comment_create|date:'d F Y, H:i' }} &lowast; </a>
    <h4> {{ comments.comment_text|censor }} </h4>
    <strong> Поставь лайк {{ comments.comment_rating }} </strong>
    <br>
    <p><q>&lowast;&lowast;&lowast;</q></p>
    {% endfor %}
    {% else %}
    <h3>NO COMMENT</h3>
    {% endif %}


    <div>
        <h2> Добавить новый комментарий </h2>
        <form action="" style="text-align: center;" method="post">
            {% csrf_token %}
            {% for f in form %}
            <p><label class="form-label" for="{{f.ai_for_label}}">{{f.label}}: </label> {{ f }} </p>
            <div class="form-error">{{ f.errors }}</div>
            {% endfor %}
            <input type="submit" value="Submit">
        </form>
    </div>

</div>


{% endblock %}

news/templates/news/post_form.html
{% extends 'default.html' %}
{% load custom_filters %}

{% block title %} CREATE {% endblock %}
{% block header %}
Здесь вы сможете опубликовать свою новость или статью
{% endblock header %}


{% block content %}
<strong> {{ post_create_view.headline }}</strong>

<!--====================================-->

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-xl-10 mx-auto">
            <h2 style="text-align: center;">Заполните форму </h2><br>
            <form style="text-align: center;" method="post">
                {% csrf_token %}
                <br>

                <p><strong> Выберите категорию: {{ form.post_category }} </strong></p>
                <p><strong> Выберите тип: {{ form.position }}</strong></p>
                <p><strong>{{ form.headline }}</strong></p>
                <p><strong>{{ form.post_text }}</strong></p>
                <input type="submit" value="Создать пост">
            </form>

        </div>
    </div>
</div>


{% endblock %}}

news/templates/news/post_list.html
{% extends 'default.html' %}
{% load custom_filters %}
{% block title %} NewsPortal {% endblock %}

{% block content %}
<div class="container">
    <h1> {{ time_now|date:'d F Y H:i'}}</h1>
    <p class="lead">Новостей на странице: {{ post_list|length }}</p>
    {% if user.is_anonymous %}
        <b>Желаете подписаться?</b>
        <b>Пожалуйста, <a href="{% url 'account_login' %}?next{{ request.path }}">авторизуйтесь.</a></b>
    {% else %}
    <div>
        {% for c in category_name %}
        <strong><q><a href="{% url 'category_detail' c.pk %}"> {{ c.category_name }} </a></q></strong>
        {% endfor %}
    </div>
    {% endif %}
</div>
<br>
<div class="container">
    <table class="table" style="margin: auto; width: auto">
        <thead>
        <tr>
            <th>ЗАГОЛОВОК</th>
            <th>ДАТА ПУБЛИКАЦИИ</th>
            <th>ТЕКСТ ПОСТА</th>
            <th>РЕЙТИНГ ПОСТА</th>
            <th>АВТОР ПОСТА</th>
            <th>РЕЙТИНГ АВТОРА</th>
            <th>ТИП</th>
        </tr>
        </thead>
        <tbody>
        {% if post_list %}
        {% for p in post_list %}
        <tr>
            <td><a href="{{ p.get_absolute_url }}"> {{ p.headline|censor }} </a></td>
            <td>{{ p.create_date|date:'d F Y' }}</td>
            <td>{{ p.post_text|truncatechars:50|censor }}</td>
            <td><b>{{ p.post_rating }}</b></td>
            <td>{{ p.post_author.author_user.first_name}} {{p.post_author.author_user.last_name}}</td>
            <td> {{ p.post_author.author_rating }}</td>
            <td> {{ p.get_position_display }} </td>
        </tr>
        {% endfor %}
        <tbody>
    </table>
    {% else %}
    <h2> NEWS OUTPUT </h2>
    {% endif %}
</div>
<br>
<a class="btn btn-info" href="{% url 'post_create_view' %}">Добавить свой пост</a>


{% include "pagination.html" %}


{% endblock %}